In [1]:
print('hello world!')

hello world!


In [1]:
import numpy as np

In [3]:
#打印numpy的版本和配置说明
print(np.__version__)
np.show_config()

1.15.1
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/summer/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/summer/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/summer/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/summer/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/summer/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/summer/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/summer/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/summer/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/summer/anacon

In [5]:
#打印长度为10的空向量
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
Z = np.arange(10,50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
Z= np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [14]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
Z = np.random.random((3,3,3))
print(Z)

0.041769743940357706 0.9928249780687493
[[[0.49597293 0.8923337  0.14805249]
  [0.52811039 0.66400736 0.86316527]
  [0.22277094 0.55353724 0.99282498]]

 [[0.89995461 0.13717833 0.20186453]
  [0.962243   0.37593377 0.0986611 ]
  [0.39530831 0.61033574 0.61118241]]

 [[0.71139085 0.22859566 0.88468979]
  [0.26084834 0.68392691 0.61509035]
  [0.97091378 0.04176974 0.64939954]]]


In [20]:
Z = np.random.random((10,10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)
#print(Z)

0.004201259924556888 0.9997053486818633


In [21]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [22]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [2]:
import numpy as np
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5135282623269285


In [3]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [4]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [4]:
import numpy as np
print(0 * np.nan)

nan


In [5]:
print(np.nan == np.nan)

False


In [6]:
print(np.inf > np.nan)

False


In [7]:
print(np.nan - np.nan)

nan


In [8]:
print(0.3 == 3 * 0.1)

False


In [9]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [11]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [12]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [13]:
print(np.unravel_index(100,(6,7,8)))


(1, 5, 4)


In [14]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.66254592 0.85048921 1.         0.90460037 0.63246009]
 [0.86028552 0.62887501 0.22938946 0.63943885 0.80024551]
 [0.24356954 0.51940686 0.57508715 0.65622392 0.72730649]
 [0.02642597 0.79206407 0.1972461  0.30761342 0.82459433]
 [0.86229441 0.62563239 0.4303181  0.         0.97324291]]


In [18]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),                   
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [19]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [20]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [21]:
print(sum(range(5),-1))


9


In [22]:
from numpy import *
print(sum(range(5),-1))

10


In [23]:
Z = np.arange(5)
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [25]:
Z = np.arange(5)
Z <- Z 

array([False, False, False, False, False])

In [26]:
Z = np.arange(5)
Z/1/1 

array([0., 1., 2., 3., 4.])

In [27]:
print(np.array(0) / np.array(0))

nan


/Users/summer/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [28]:
print(np.array(0) // np.array(0))

0


/Users/summer/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [29]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


In [30]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 8.  9. -8.  8.  2.  8. 10. -8. -2. -4.]


In [31]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[4 6 7]


In [35]:
#Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [36]:
# Back to sanity
_ = np.seterr(**defaults)

In [39]:
An equivalent way, with a context manager:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-39-12c4e726571b>, line 1)

In [40]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [41]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [43]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [44]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 5. 0. 5. 3. 8. 1. 9. 9. 2.]
[1. 5. 0. 5. 3. 8. 1. 9. 9. 2.]
[1. 5. 0. 5. 3. 8. 1. 9. 9. 2.]
[1 5 0 5 3 8 1 9 9 2]
[1. 5. 0. 5. 3. 8. 1. 9. 9. 2.]


In [45]:
def generate():
    for x in range(10):
        yield x 
        Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[1.27934617 5.20658116 0.85668334 5.20919329 3.53454828 8.83407245
 1.9891014  9.21790687 9.8189056  2.74807559]


In [46]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [47]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.0225137  0.04060919 0.08708282 0.09301757 0.35326597 0.39179312
 0.41031487 0.43718308 0.49771942 0.96680352]


In [48]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [49]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [50]:
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False


In [51]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [52]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[0.67453747 0.30200183 0.31789454 0.44375338 1.16445826 0.85831741
 0.72134726 0.80761175 1.10241675 0.80924829]
[0.80846232 0.54922484 1.19062361 1.06246137 0.98575074 0.38574431
 0.9861379  0.57164975 0.96814233 0.89971599]


In [53]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.64054394 0.         0.46153376 0.4248559  0.46930828 0.43380225
 0.63382268 0.61483023 0.39164003 0.23609139]


In [54]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [55]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [56]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [57]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
Z = np.arange(100)
v = np.random.uniform(0,100) 
index = (np.abs(Z-v)).argmin()
print (Z[index])

43


In [59]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [60]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.54523603 0.32612952 0.41373502 0.54703463 0.53651559
  0.33713102 0.31224006 0.7730717  0.00120512]
 [0.54523603 0.         0.61916784 0.75109802 0.08232296 0.78876443
  0.83335978 0.81061047 0.55846515 0.54475838]
 [0.32612952 0.61916784 0.         0.13231028 0.6625926  0.21631859
  0.29991985 0.28838135 0.56613862 0.32499835]
 [0.41373502 0.75109802 0.13231028 0.         0.79486639 0.14172792
  0.25628133 0.25588208 0.64119561 0.41275639]
 [0.54703463 0.08232296 0.6625926  0.79486639 0.         0.84370943
  0.85407085 0.83045764 0.64059928 0.54672874]
 [0.53651559 0.78876443 0.21631859 0.14172792 0.84370943 0.
  0.39250726 0.3947518  0.5690752  0.53544244]
 [0.33713102 0.83335978 0.29991985 0.25628133 0.85407085 0.39250726
  0.         0.02489503 0.8658641  0.33679836]
 [0.31224006 0.81061047 0.28838135 0.25588208 0.83045764 0.3947518
  0.02489503 0.         0.85443112 0.31190595]
 [0.7730717  0.55846515 0.56613862 0.64119561 0.64059928 0.5690752
  0.8658641  0.8544311

In [61]:
# Much faster with scipy
import scipy
# # Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print (D)

[[0.         0.54523603 0.32612952 0.41373502 0.54703463 0.53651559
  0.33713102 0.31224006 0.7730717  0.00120512]
 [0.54523603 0.         0.61916784 0.75109802 0.08232296 0.78876443
  0.83335978 0.81061047 0.55846515 0.54475838]
 [0.32612952 0.61916784 0.         0.13231028 0.6625926  0.21631859
  0.29991985 0.28838135 0.56613862 0.32499835]
 [0.41373502 0.75109802 0.13231028 0.         0.79486639 0.14172792
  0.25628133 0.25588208 0.64119561 0.41275639]
 [0.54703463 0.08232296 0.6625926  0.79486639 0.         0.84370943
  0.85407085 0.83045764 0.64059928 0.54672874]
 [0.53651559 0.78876443 0.21631859 0.14172792 0.84370943 0.
  0.39250726 0.3947518  0.5690752  0.53544244]
 [0.33713102 0.83335978 0.29991985 0.25628133 0.85407085 0.39250726
  0.         0.02489503 0.8658641  0.33679836]
 [0.31224006 0.81061047 0.28838135 0.25588208 0.83045764 0.3947518
  0.02489503 0.         0.85443112 0.31190595]
 [0.7730717  0.55846515 0.56613862 0.64119561 0.64059928 0.5690752
  0.8658641  0.8544311

In [62]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [66]:
#genfromtxt 读取文件
'''
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
'''
from io import StringIO
import  numpy  as  np
s = StringIO("1,1.3,abcde")
data = np.genfromtxt(s, dtype=[('myint','i8'),('myfloat','f8'),('mystring','S5')], delimiter=",")
print(data)

(1, 1.3, b'abcde')


In [64]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [67]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [68]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [69]:
Y = X - X.mean(axis=1).reshape(-1, 1)
print (Y)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


In [70]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-2.56210523e-01  1.30320225e-01 -3.71443364e-01 -6.07075576e-02
   5.12061448e-02  1.05816799e-01  5.61520523e-01  1.68322831e-01
  -1.73715081e-02 -3.11453570e-01]
 [ 4.44588326e-01  5.83650502e-02  2.77205939e-01 -1.12793144e-01
  -3.07048662e-01  5.12037462e-01 -1.10574560e-01 -3.88769556e-01
  -2.79347501e-02 -3.45076106e-01]
 [-1.55059477e-01  3.20090521e-01  1.56793916e-01 -1.19039765e-01
   2.54968255e-01 -5.95999436e-01 -5.25339449e-02 -2.13706116e-02
   3.14148958e-02  1.80735646e-01]
 [ 1.11046671e-01 -1.87534371e-02  2.46984160e-01 -1.60565910e-01
  -2.56757357e-01 -1.36191649e-01 -8.69687351e-02 -1.49325791e-01
   2.41878427e-01  2.08653620e-01]
 [-2.19149870e-04 -3.32925603e-01  1.92089506e-02  2.63805705e-01
  -1.43757971e-02 -4.01182473e-01  1.01359792e-01  3.50086536e-01
   3.31643363e-01 -3.17401324e-01]]


In [71]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[4 4 4]
 [9 4 7]
 [0 8 3]]
[[4 4 4]
 [9 4 7]
 [0 8 3]]


In [72]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


In [73]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.33510065842272097


In [74]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [75]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [76]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 2. 2. 3. 4. 3. 2. 2. 4. 4.]


In [78]:
np.add.at(Z, I, 1)
print(Z)

[10.  4.  4.  7. 10.  7.  4.  4. 10. 10.]


In [79]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [80]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [81]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[51 68 67 74]
 [46 59 59 81]
 [62 38 54 43]]


In [82]:
 sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

[[51 68 67 74]
 [46 59 59 81]
 [62 38 54 43]]


In [83]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.5501998  0.48927278 0.5626203  0.56884318 0.60078605 0.46542734
 0.40148249 0.4389421  0.43931984 0.32249697]


In [84]:
import pandas as pd
print(pd.Series(D).groupby(S).mean())

0    0.550200
1    0.489273
2    0.562620
3    0.568843
4    0.600786
5    0.465427
6    0.401482
7    0.438942
8    0.439320
9    0.322497
dtype: float64


In [85]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))

array([1.35170181, 1.79966911, 1.20476394, 1.26528269, 1.91309685])

In [86]:
np.sum(A * B.T, axis=1)

array([1.35170181, 1.79966911, 1.20476394, 1.26528269, 1.91309685])

In [87]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [88]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [89]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [90]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 0, 34) ( 0, 39) ( 7,  8) ( 7, 65) ( 8, 65) (15, 27) (15, 55) (22, 39)
 (22, 80) (22, 97) (22, 98) (27, 55) (29, 47) (29, 57) (32, 35) (32, 50)
 (34, 39) (35, 50) (39, 97) (47, 57) (48, 60) (48, 67) (57, 73) (57, 87)
 (60, 67) (73, 87) (78, 85) (78, 99) (80, 98) (85, 99)]


In [91]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [92]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [93]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)     
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [94]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0])

In [95]:
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.48294345,  0.71352846,  0.16230345, -0.16670965, -0.02598303,
       -0.00404115,  0.781139  ,  0.18411573,  0.12272553, -0.68487254,
        0.67234249,  0.90984279, -0.45689425,  0.67017066, -0.71983882,
        0.0850957 , -0.9045467 , -0.45866031,  0.3905742 , -0.18603134,
       -0.00570302, -0.08584737, -0.78127504, -0.22774871, -0.73010616,
        0.39533742, -0.19135073,  0.72849013, -0.61496714, -0.84806892,
       -0.27756475,  0.02672176,  0.97795146, -0.1510947 ,  0.55998123,
       -0.82401744,  0.43527444,  0.43963407,  0.77747431, -0.73138891,
       -0.86632189,  0.62210792, -0.93170407, -0.41694004,  0.45924908,
        0.74966767, -0.06962833,  0.77088956,  0.45196519,  0.23388992,
        0.11184943,  0.36759436, -0.64902552,  0.83986174, -0.46899518,
        0.56472061, -0.1299585 ,  0.69155469, -0.6183757 , -0.85943844,
       -0.4327391 ,  0.34858813,  0.20327478,  0.37508557, -0.43163785,
        0.19485706, -0.25082978, -0.52190579, -0.81040438,  0.83

In [96]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[13.01699652  3.22575956  4.14774386  5.87395215  4.96227448  7.63203033
  2.65894805  3.90707748  9.36177639  2.47151496]


In [97]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.30472081  9.29925454  4.00896297 11.40027888  2.77990895  0.68757827
   2.1481642   0.02401756  6.26261195  7.00515778]
 [11.52749776  0.16961226 12.79480106  0.56840154  6.17755083  9.19388674
  10.96397038  9.35593875  3.05772137  1.71544062]
 [ 2.98474208  7.07031315  6.72369159 10.31596215  0.18287924  6.2150757
   5.43847207  2.35422211  3.92393289 14.14147619]
 [11.10035992  2.58836472 15.54869901  1.04345048  8.8506769   4.34791762
   9.28718803 11.84493264  5.55258473  6.97043813]
 [ 8.74843863  2.8234777  16.13418078  0.47984465  9.35060158  0.49997294
   5.98994921 12.15248892  5.8662175  11.60078065]
 [ 2.65233696 10.07165479  2.60401413 10.7238873   4.03056412  9.47296095
   3.57032874  0.87932033  7.17692924  1.48534032]
 [ 1.15027361  6.05747871  7.59993619  9.01334106  0.72725703  4.43022328
   3.40936664  3.33929095  2.94120423 12.75212398]
 [11.66342587  0.1346607  12.43706184  0.74554349  5.83273699  9.95920872
  11.28640993  9.04049525  2.74134362  0.90781791]
 

In [98]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [99]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[9 9 4 2 5 7 0 0 2 8]
 [9 0 3 2 8 8 9 4 8 4]
 [3 6 7 1 1 7 2 1 3 7]
 [8 8 0 2 9 1 5 5 5 1]
 [7 6 7 9 5 3 2 8 7 8]
 [1 5 0 8 9 6 0 3 2 8]
 [4 8 8 0 2 0 9 3 2 0]
 [0 9 3 5 1 0 7 0 6 3]
 [2 4 9 5 8 8 7 6 3 0]
 [8 7 2 7 4 4 8 0 8 5]]
[[0 0 0 0 0]
 [0 9 9 4 2]
 [0 9 0 3 2]
 [0 3 6 7 1]
 [0 8 8 0 2]]


/Users/summer/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [100]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [102]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

3


In [103]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[0 2 2]
   [2 4 2]
   [4 0 2]]

  [[2 2 0]
   [4 2 1]
   [0 2 0]]

  [[2 0 0]
   [2 1 3]
   [2 0 0]]

  [[0 0 1]
   [1 3 2]
   [0 0 0]]

  [[0 1 2]
   [3 2 0]
   [0 0 0]]

  [[1 2 4]
   [2 0 1]
   [0 0 1]]

  [[2 4 1]
   [0 1 2]
   [0 1 4]]

  [[4 1 1]
   [1 2 3]
   [1 4 1]]]


 [[[2 4 2]
   [4 0 2]
   [1 0 1]]

  [[4 2 1]
   [0 2 0]
   [0 1 0]]

  [[2 1 3]
   [2 0 0]
   [1 0 3]]

  [[1 3 2]
   [0 0 0]
   [0 3 3]]

  [[3 2 0]
   [0 0 0]
   [3 3 2]]

  [[2 0 1]
   [0 0 1]
   [3 2 4]]

  [[0 1 2]
   [0 1 4]
   [2 4 3]]

  [[1 2 3]
   [1 4 1]
   [4 3 0]]]


 [[[4 0 2]
   [1 0 1]
   [3 2 1]]

  [[0 2 0]
   [0 1 0]
   [2 1 0]]

  [[2 0 0]
   [1 0 3]
   [1 0 0]]

  [[0 0 0]
   [0 3 3]
   [0 0 3]]

  [[0 0 0]
   [3 3 2]
   [0 3 2]]

  [[0 0 1]
   [3 2 4]
   [3 2 4]]

  [[0 1 4]
   [2 4 3]
   [2 4 1]]

  [[1 4 1]
   [4 3 0]
   [4 1 2]]]


 [[[1 0 1]
   [3 2 1]
   [3 3 1]]

  [[0 1 0]
   [2 1 0]
   [3 1 2]]

  [[1 0 3]
   [1 0 0]
   [1 2 4]]

  [[0 3 3]
   [0 0 3]
   [2 4 4]]

  [[3 3 2]
   

In [104]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 4 12 10 13  1]
 [12  9 13  7 16]
 [10 13  4 42  5]
 [13  7 42  1  9]
 [ 1 16  5  9  4]]


In [106]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)
# It works, because:
M is (p,n,n)
V is (p,n,1)
#Thus, summing over the paired axes 0 and 0 (of M and V independently),
#and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


False

In [107]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [109]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


In [110]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
